### ISSUE TITLE
分辨率问题

### ISSUE THREAD

**Issue by windyhun** [PC6live/bilibili-joybook-tampermonkey#12]
有时候打开视频分辨率那是自动的（而且无法手动选择4k，点分辨率没反应）
![20220617025806](https://user-images.githubusercontent.com/46866712/174145137-e784e09b-ecd8-498d-a57a-534d75018272.png)

**Comment by windyhun** [comment]
刷新和重新进页面都不行

**Comment by windyhun** [comment]
不过，可以点视频的右边的推荐视频（推荐视频正常4k）然后再返回就能正常。
![image](https://user-images.githubusercontent.com/46866712/174145527-808b8308-7264-494b-8592-be65965c196e.png)

**Comment by PC6live** [comment]
[
![image](https://user-images.githubusercontent.com/33170097/174263273-b595926f-7f83-4907-a4c1-7ee2c0a8c2d2.png)
](url) 你这是有使用其他插件吗？

**Comment by windyhun** [comment]
Bilibili Evolved
![image](https://user-images.githubusercontent.com/46866712/179399109-3ad20aff-eea9-4dd1-b26e-beafe5bcc19b.png)
启用了这些脚本

**Comment by PC6live** [comment]
你更新一下我的脚本，然后禁用其他脚本看看有没有问题，有的话我有时间再做兼容了
