### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by Air433up** [PC6live/bilibili-joybook-tampermonkey#14]
请问作者大大能否直接使用cookie写到脚本里去，有大会员cookie

**Comment by PC6live** [comment]
可以，你在tempermonkey 脚本->储存那里，照着userCookie建立vipCookie里面写上SESSDATA就行

**Comment by Air433up** [comment]
> 可以，你在tempermonkey 脚本->储存那里，照着userCookie建立vipCookie里面写上SESSDATA就行

建立后提示如下
![-53ccf92e47d4f348.png](https://user-images.githubusercontent.com/60246381/174479979-e3df0926-60d8-414b-b45e-d822c4fa347f.png)

**Comment by PC6live** [comment]
![image](https://user-images.githubusercontent.com/33170097/174480351-3fbbea61-ae6a-484f-8a70-ae3853a4d07c.png)
如果你的是这样的话，还不行就是cookie过期了，建议你还是按照wiki弄

**Comment by Air433up** [comment]
我是这样写的
![IMG_20220619_201745.png](https://user-images.githubusercontent.com/60246381/174480537-acaf6749-b4b4-4d4a-976f-38e2acab1fde.png)

**Comment by PC6live** [comment]
必须得写完全才行

**Comment by Air433up** [comment]
> 必须得写完全才行

expirationDate这个值如何确定

**Comment by PC6live** [comment]
过期时间，你弄个和userCookie一样的就行了

**Comment by PC6live** [comment]
过期时间，你弄个和userCookie一样的就行了

**Comment by Air433up** [comment]
解决了，感谢作者大大

**Comment by Air433up** [comment]
哦，对了，似乎番剧无法切换成1080p高码率，手动切换直接显示切换失败，不知道是啥原因，但是普通视频可以自由切换

**Comment by PC6live** [comment]
无法判断，我的这边正常
