### ISSUE TITLE
弹幕设置

### ISSUE THREAD

**Issue by Y0J1G3N** [PC6live/bilibili-joybook-tampermonkey#16]
大会员的弹幕设置与普通会员不一致，播放视频时经常互换，能否设置成普通会员的弹幕设置？

**Comment by PC6live** [comment]
我不发弹幕，能不能讲详细一点，想要什么样的效果

**Comment by Y0J1G3N** [comment]
我的情况是这样的：大会员的弹幕设置为，不透明度=80%，普通会员的弹幕设置不透明度=100%。播放视频的时候，有时会用大会员的弹幕设置，有时是普通会员的弹幕设置。希望播放视频时，应用普通会员的弹幕设置？
<img width="241" alt="Screenshot 2022-08-15 160541" src="https://user-images.githubusercontent.com/43652659/184599631-7dd5b1d4-6b36-4bb9-b0e1-adde8b39229e.png">
<img width="246" alt="image" src="https://user-images.githubusercontent.com/43652659/184599721-11d174ed-5591-43f8-bd1d-e129c08c6486.png">

**Comment by Y0J1G3N** [comment]
使用正常，谢谢。
