### ISSUE TITLE
添加其他人的cookie后创作中心无法使用

### ISSUE THREAD

**Issue by Stardust-minus** [PC6live/bilibili-joybook-tampermonkey#18]
如题。
先是打开后白屏，后设置排除https://member.bilibili.com/ 后正常。
但无法进行点赞等操作，显示
![image](https://user-images.githubusercontent.com/52093397/188263436-a51c2de0-319e-42cc-b3eb-2df2728d7447.png)

**Comment by PC6live** [comment]
csrf问题暂时无法解决，只能重置脚本重新登录
