### ISSUE TITLE
0.0.9版本无法使用

### ISSUE THREAD

**Issue by Y0J1G3N** [PC6live/bilibili-joybook-tampermonkey#23]
获取播放地址...
播放器初始化... [成功] 3.23.9-aa2cfd24
收到一条消息... [警告] 加载即将超时(9s)，若有疑问，请反馈问题（点击右上角按钮进行反馈）
加载内容超时... 请尝试禁用所有浏览器插件后，刷新本页面

**Comment by Y0J1G3N** [comment]
还更新吗？几个月不能用了。

**Comment by PC6live** [comment]
我没有会员帐号了，没法 debug 。

**Comment by Y0J1G3N** [comment]
![image](https://user-images.githubusercontent.com/43652659/221223774-286845cf-baca-44ad-8fbd-9c1d35834f49.png)
所有视频都显示加载中，无法观看。但是使用https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5就能用了。
试过重装Chrome，重新登录也是这样的情况。所有视频都显示加载中。

**Comment by PC6live** [comment]
按F12给我看一下输出

**Comment by Y0J1G3N** [comment]
![image](https://user-images.githubusercontent.com/43652659/221227063-685e6139-cae6-473e-bdb2-dc997ed9e15f.png)
![image](https://user-images.githubusercontent.com/43652659/221227114-ac94d19b-1b25-463a-a495-ddd65e9f9385.png)

**Comment by PC6live** [comment]
你可以试一下点击左下角头像清除数据后，不要开其他脚本，再登录一次看看。

**Comment by Y0J1G3N** [comment]
你好，我试了在edge里能正常使用，但是chrome用不了，左下角也没有用户头像。同样使用chromium也不能使用，和chromium的情况一样。现在不知道是哪出了问题。

**Comment by PC6live** [comment]
chrome之前有用过这个脚本吗？可能是有一个数据写死了，导致左下角没有头像，删掉脚本再装一次试试。

**Comment by Y0J1G3N** [comment]
有重装过，以为是自己浏览器设置问题，然后下载https://github.com/Hibbiki/chromium-win64安装插件和脚本，也出现和chrome一样的问题。没安装脚本前，我按照操作说明先登录了大会员的账号，安装脚本后，登录普通会员账号。也试过没安装脚本前，先登录普通会员账号，再安装脚本，再登录大会员账号，最后登录普通会员账号。

**Comment by PC6live** [comment]
我刚刚试了一下，最新 chrome 确实有问题，edge就可以。

**Comment by PC6live** [comment]
修复了，你试一下。

**Comment by Y0J1G3N** [comment]
能用了，感谢！
