### ISSUE TITLE
链锯人最新一集看不了

### ISSUE THREAD

**Issue by liumuyv** [PC6live/bilibili-joybook-tampermonkey#24]
看第一集显示已经加载了高码率清晰度，切换最新集会强行加了个大会员遮罩
国内会员番剧正常，视频清晰度解锁正常

**Comment by PC6live** [comment]
![image](https://user-images.githubusercontent.com/33170097/208814323-bdb3b42a-7d6f-4d7d-8293-3e49092dfdfb.png)
你是使用了其他的区域解锁脚本吧，我直接挂代理看就没事

**Comment by liumuyv** [comment]
啊，发现是啥问题了，我bilibili evolved开启了默认播放器模式是宽屏模式，这个界面点宽屏就会显示要大会员
