### ISSUE TITLE
登录一个账号后无法自动刷新

### ISSUE THREAD

**Issue by liumuyv** [PC6live/bilibili-joybook-tampermonkey#33]
左下角始终是空白头像，没法再次登录另一个账号
Microsoft Edge版本 114.0.1823.58 (正式版本) (64 位)

**Comment by PC6live** [comment]
使用相同版本测试，并未发现此问题。

**Comment by liumuyv** [comment]
貌似和其他去广告拓展冲突了，我把所有拓展全部关闭后正常了，然后又全部一个个打开之后还是正常，可能是偶发性的bug
