### ISSUE TITLE
希望能添加手動輸入

### ISSUE THREAD

**Issue by tkp206093** [PC6live/bilibili-joybook-tampermonkey#41]
https://zmtblog.xdkd.ltd/2021/10/06/Get_bilibili_cookie/

**Comment by PC6live** [comment]
暂不考虑，实在需要的话可以油猴开高级设置去改脚本储存
![image](https://github.com/user-attachments/assets/ad07af84-e33e-4454-a7b2-b724aa39c47b)

**Comment by tkp206093** [comment]
> 暂不考虑，实在需要的话可以油猴开高级设置去改脚本储存 ![image](https://private-user-images.githubusercontent.com/33170097/367289648-ad07af84-e33e-4454-a7b2-b724aa39c47b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzU1MDgsIm5iZiI6MTcyNjIzNTIwOCwicGF0aCI6Ii8zMzE3MDA5Ny8zNjcyODk2NDgtYWQwN2FmODQtZTMzZS00NDU0LWE3YjItYjcyNGFhMzljNDdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDEzNDY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNTczYjYyYjU3YWMwNzgwMDhkNzZhNjY3MWU1MTBhNGVhNDZmOTE0OTM1YmM2NmM3MTU4ZjAxYWE1ZTI2MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iRRo3rLL3UocNsCYP2T-kvDi0iz_FUlKjFtN12QQGT8)

試了 不知道為何不成

**Comment by PC6live** [comment]
![image](https://github.com/user-attachments/assets/9efb3d8e-1ab9-44bd-9ea3-cba69b49804f)
我没有截取全部图片，主要是 vipCookie 的 SESSDATA，你还是用使用说明的方法操作吧，手动配置这个储存还是很麻烦的。
