### ISSUE TITLE
如何使用?

### ISSUE THREAD

**Issue by xyjtyskfydhqss** [PC6live/bilibili-joybook-tampermonkey#43]
> 操作说明
> 1. 登录账号。
> 2. 等待自动刷新直到可以再次登录。
> 3. 确认左下角出现刚才登陆过的账号头像（普通用户蓝色边框，大会员用户粉红边框）。
> 4. 登录另一个账号（第一步是会员账户，则登录你的账户，反之亦然）。
> 5. 刷新。

1. 登录账号. 完成后没有自动刷新, 登录的大会员账号, 自始至终都是一个蓝色边框.
2. 没有自动刷新......

**Comment by PC6live** [comment]
请提供更多信息，登录账号确定为会员账号，使用的是否为 Tampermonkey beta。

**Comment by xyjtyskfydhqss** [comment]
参照 #41 手动设置了 userCookie / vipCookie 还是不行

![image](https://github.com/user-attachments/assets/d1640faf-a07b-4212-b6ad-d9ff94df983a)

值是用 EditThisCookie 插件导出的, 我对了一下字段也是一样的

**Comment by PC6live** [comment]
![image](https://github.com/user-attachments/assets/5e2b311f-7104-4c1c-9515-8b3ae918ae5d)
你打开devtools看看有没有这个信息

**Comment by xyjtyskfydhqss** [comment]
别的脚本管理器还真不行, 我习惯用暴力猴, 界面简单

**Comment by PC6live** [comment]
其他扩展可能没有实现对cookie的操作，所以不行。

**Comment by xyjtyskfydhqss** [comment]
感谢解答~
