### ISSUE TITLE
希望默认画质为最高

### ISSUE THREAD

**Issue by junMars** [PC6live/bilibili-joybook-tampermonkey#6]
希望大佬能改一下，把普通视频的默认画质调到最高。不然每次视频都要点一下有点麻烦了。谢谢大佬！！！！！！！！！

**Comment by PC6live** [comment]
更新了，你试试行不行

**Comment by junMars** [comment]
还是普通视频打开默认高清，不会自动开启高帧率或者高码率。现在还出现一个bug了。手动切换画质有很大几率切换失败。感谢大佬!!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PC6live/bilibili-joybook-tampermonkey"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月19日(星期三) 晚上9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PC6live/bilibili-joybook-tampermonkey] 希望默认画质为最高 (#6)





 
更新了，你试试行不行
