### ISSUE TITLE
出了新bug

### ISSUE THREAD

**Issue by junMars** [PC6live/bilibili-joybook-tampermonkey#7]
现在会自动默认最高画质，但是实际上还是1080p普通视频。没有实际效果
![QQ图片20210520221141](https://user-images.githubusercontent.com/44231875/118994299-ca0e7c00-b9b8-11eb-97e6-e5ff436dd60c.png)

**Comment by PC6live** [comment]
现在可以了，你可能需要清理一下b站的cookie，之前我锁定过画质的cookie

**Comment by junMars** [comment]
> 现在可以了，你可能需要清理一下b站的cookie，之前我锁定过画质的cookie

已经可以了，感谢大佬
