### ISSUE TITLE
Tampermonkey BETA 无任何显示....

### ISSUE THREAD

**Issue by qwuae1** [PC6live/bilibili-joybook-tampermonkey#8]
Tampermonkey BETA 无任何显示....
不知道是不是海外需要其他插件解锁地区锁的原因
插件也没有生效
没有任何显示...

是直接账号信息写进cookie里了嘛？
没细看。。。我这直接什么都没有。。。

**Comment by qwuae1** [comment]
![image](https://user-images.githubusercontent.com/36930393/137058151-40b40a17-88b4-4f3f-abb9-75cab3b430ef.png)
....就是一直连UI都没有。。。一度怀疑插件没有UI
账号登出正常...
log都在图片里

**Comment by PC6live** [comment]
你第二步登录自己账号有没有做
